targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
      - test/**
    builders:
      freezed:
        options:
          when:
            when: false
            maybe_when: false
            when_or_null: false
