name: yuno
description: A Yuno Task Management
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  rxdart: ^0.27.7

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # Network
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1

  # Routers
  go_router: ^10.1.0

  # Local
  shared_preferences: ^2.2.0

  # DI
  get_it: ^7.6.0

  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  loader_overlay: ^2.3.1
  convex_bottom_bar: ^3.2.0
  percent_indicator: ^4.2.3
  flutter_datetime_picker_plus: ^2.0.1

  # Utils
  logging: '>=1.1.0 <1.2.0'
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  email_validator: ^2.1.17
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  file_picker: ^5.3.3
  crypto: ^3.0.3

  # Firebase
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  carapacik_lints: ^1.4.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  retrofit_generator: ^7.0.8
  swagger_parser: ^1.2.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/avatars/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true

# start: flutter pub run swagger_parser:generate
swagger_parser:
  schema_path: assets/swagger.json # Required. Sets the json path directory for api definition. This is just a suggestion for path
  output_directory: lib/api2 # Required. Sets output directory for generated files (api clients and models)
  language: dart # Optional. Sets the programming language. Current available languages are: dart, kotlin. Default: dart
  squish_clients: false # Optional. Set 'true' to put all clients in one folder. Default: false
  client_postfix: ApiClient # Optional. Set postfix for client folder and Class. Works if there is only a single class or squish is true. Default: Client
  freezed: true # Optional (dart only). Set 'true' to generate data classes using freezed package. Default: false
