name: yuno
description: Yuno
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_gen: ^5.1.0+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  equatable: ^2.0.5
  email_validator: ^2.1.17

dev_dependencies:
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/resources/
