name: yuno
description: Yuno
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_gen: ^5.1.0+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.5
  email_validator: ^2.1.17
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7

  # Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1

  # Local
  shared_preferences: ^2.0.15

  # DI
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  swagger_parser: ^0.5.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/resources/


swagger_parser:
  json_path: assets/swagger.json # Required. Sets the json path directory for api definition. This is just a suggestion for path
  output_directory: lib/api2 # Required. Sets output directory for generated files (api clients and models)
  language: dart # Optional. Sets the programming language. Current available languages are: dart, kotlin. Default: dart
  squish_clients: false # Optional. Set 'true' to put all clients in one folder. Default: false
  client_postfix: ApiClient # Optional. Set postfix for client folder and Class. Works if there is only a single class or squish is true. Default: Client
  freezed: true # Optional (dart only). Set 'true' to generate data classes using freezed package. Default: false