name: yuno
description: A Yuno Task Management
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  flutter:
    sdk: flutter
  #  flutter_gen: ^5.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.27.7

  # State management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  # Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1

  # Routers
  # go_router: ^6.0.1
  go_router_flow: ^6.0.0+3

  # Local
  shared_preferences: ^2.0.17

  # DI
  get_it: ^7.2.0

  # UI
  flutter_svg: ^2.0.0+1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.1.2
  loader_overlay: ^2.1.0
  convex_bottom_bar: ^3.2.0
  percent_indicator: ^4.2.2
  flutter_datetime_picker: ^1.5.1

  # Utils
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5
  email_validator: ^2.1.17
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  file_picker: ^5.2.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  swagger_parser: ^0.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true

swagger_parser:
  schema_path: assets/swagger.json # Required. Sets the json path directory for api definition. This is just a suggestion for path
  output_directory: lib/api2 # Required. Sets output directory for generated files (api clients and models)
  language: dart # Optional. Sets the programming language. Current available languages are: dart, kotlin. Default: dart
  squish_clients: false # Optional. Set 'true' to put all clients in one folder. Default: false
  client_postfix: ApiClient # Optional. Set postfix for client folder and Class. Works if there is only a single class or squish is true. Default: Client
  freezed: true # Optional (dart only). Set 'true' to generate data classes using freezed package. Default: false
